version: "3.9"
services:
  redpanda:
    image: redpandadata/redpanda:latest
    command: >
      redpanda start --overprovisioned --smp 1 --memory 1G --reserve-memory 0M
      --check=false --set redpanda.auto_create_topics_enabled=true
    ports: ["9092:9092","9644:9644"]

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ../migrations/0001_init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    ports: ["5432:5432"]

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on: [postgres, redpanda]
    environment:
      KAFKA_BROKERS: "redpanda:9092"
      KAFKA_TOPIC: "orders"
      KAFKA_GROUP: "orders-consumer"
      DB_DSN: "postgres://orders_user:orders_pass@postgres:5432/ordersdb?sslmode=disable"
      CACHE_SIZE: "1000"
      HTTP_ADDR: ":8081"
    ports: ["8081:8081"]

  adminer:
    image: adminer
    depends_on: [postgres]
    ports: ["8080:8080"]